### ISSUE TITLE
google-map-directions Uncaught TypeError

### ISSUE THREAD

**Issue by jodekirk** [googlecodelabs/polymer-maps#1]
Trying the Polymer Summit 2015 Build Good Maps tutorial with No Code gives an error on the step adding 
<google-map-directions
      start-address="San Francisco"
      end-address="Mountain View"
      libraries="places"></google-map-directions>

JavaScript error: Uncaught TypeError: m[md].maps.Load is not a function    main.js:70

The map doesn't display for the rest of the tutorial unless google-map-directions is commented out.

**Comment by ebidel** [comment]
Did you also add the libraries attr to the map element?

**Comment by jodekirk** [comment]
You are good! Sorry. I missed that step. Now it works correctly without any errors.
