### ISSUE TITLE
Loading google-map-directions without a key throws an error if the google-map was loaded with key ( "You have included the Google Maps API multiple times on this page. " )

### ISSUE THREAD

**Issue by kaskaderc** [googlecodelabs/polymer-maps#10]
Code:
```
<html>
<head>
  <title>PolymerMapsCodelab</title>
  <meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0">
  <meta name="mobile-web-app-capable" content="yes">
  <meta name="apple-mobile-web-app-capable" content="yes">
  <script src="bower_components/webcomponentsjs/webcomponents-lite.min.js"></script>
  <link rel="import" href="bower_components/google-map/google-map.html">
  <link rel="import" href="bower_components/google-map/google-map-directions.html">
  <link rel="stylesheet" href="styles.css">
</head>

<body unresolved>
    <google-map latitude="37.779" longitude="-122.3892" zoom="13"
      api-key="KEY">
       <google-map-marker latitude="37.779" longitude="-122.3892"
      title="Go Giants!" draggable="true"></google-map-marker>
    </google-map>
    <google-map-directions
      start-address="San Francisco"
      end-address="Mountain View"></google-map-directions>
</body>
</html>
```

Error:
```
You have included the Google Maps API multiple times on this page.
js?callback=https___maps_googleapis_com_maps_api_js_callback___callback___v_3_exp_libraries_drawing…:88 You have included the Google Maps API multiple times on this page. This may cause unexpected errors.Gg @ js?callback=https___maps_googleapis_com_maps_api_js_callback___callback___v_3_exp_libraries_drawing…:88(anonymous function) @ js?callback=https___maps_googleapis_com_maps_api_js_callback___callback___v_3_exp_libraries_drawing…:122google.maps.Load @ js?callback=https___maps_googleapis_com_maps_api_js_callback___callback___v_3_exp_libraries_drawing…:21(anonymous function) @ js?callback=https___maps_googleapis_com_maps_api_js_callback___callback___v_3_exp_libraries_drawing…:122(anonymous function) @ js?callback=https___maps_googleapis_com_maps_api_js_callback___callback___v_3_exp_libraries_drawing…:123
util.js:218 Google Maps API warning: NoApiKeys https://developers.google.com/maps/documentation/javascript/error-messages#no-api-keys
```

**Comment by bamnet** [comment]
Perhaps during the Polymer 0.5 -> 1.0 conversion the library de-duplication logic in google-maps-api.html from GoogleWebComponents/google-apis stopped working.

Alternatively, the `google-map` and `google-map-directions` elements could be calling google-maps-api differently resulted in two different load attempts instead of one.  Will try to investigate this week.

**Comment by ebidel** [comment]
Hmmm. The apis element loads all libs now to avoid these types of issues.  Are you using the latest elements?

**Comment by kaskaderc** [comment]
It seems like you can resolve the issue by adding the API key to the other <google-map-... elements
For example this code works fine
```
<template is="dom-bind">
    <google-map map="{{map}}" latitude="37.779" longitude="-122.3892" zoom="13"
      api-key="AIza_THIS_IS_AN_API_KEY_leM"></google-map>
    <google-map-directions map="{{map}}"
      api-key="AIza_THIS_IS_AN_API_KEY_leM"
      start-address="San Francisco"
      end-address="Mountain View"
      travel-mode="BICYCLING"
      waypoints='[{"location": "Palo Alto"}, {"location": "San Mateo"}]'></google-map-directions>
   </template>
```
while this one throws errors:
```
<template is="dom-bind">
    <google-map map="{{map}}" latitude="37.779" longitude="-122.3892" zoom="13"
      api-key="AIza_THIS_IS_AN_API_KEY_leM"></google-map>
    <google-map-directions map="{{map}}"
      start-address="San Francisco"
      end-address="Mountain View"
      travel-mode="BICYCLING"
      waypoints='[{"location": "Palo Alto"}, {"location": "San Mateo"}]'></google-map-directions>
   </template>
```
The error is:
`"You have included the Google Maps API multiple times on this page. This may cause unexpected errors."`

**Comment by ebidel** [comment]
Yes. Every maps element needs to have the api-key.

**Comment by kaskaderc** [comment]
Just to make it clear the last thing I want to do is to only complain, but I did not have time to look into the implementation details yet. Planning to do that slowly but surely :)

There are two things that need fixing. (1) Addressing loading the API multiple times and (2) fixing code samples and documentation.

(1) It seems like we need to make a call whether to allow bootstrap parameters in elements that are not <google-maps-api>. For now the basic bootstrap params (version, key , etc) is only allowed on google-map-api and google-map. The google-map-directions allows 
key but does not have version - that is already the first inconsistency.

The documentation on  [google-map-api](https://elements.polymer-project.org/elements/google-apis?active=google-maps-api) mentions 
"Any number of components can use <google-maps-api> elements, and the library will only be loaded once."
but that all falls through as soon as any of the  other elements that can have a key and a version, because any incosistency between these params will load the api again.

Yet another story is google-map-search, it does not have a key even though it could potentially be loaded without a map, so just like directions

I think the most transparent solution would be to require a  <google-maps-api> element with all the params and not try to laod the API with params from other elements (delete the key and version params from google-map and the key param from google-map-directions )

@Eric- do you think that is a good idea? Would that be hard to implement? Can you point me to a good starting point to try and do this?

(2) The sampels code should be fixed to include the key placeholder. The codelab that breaks that brought me here is [the polymer-map codelab](https://codelabs.developers.google.com/codelabs/polymer-maps/index.html?index=..%2F..%2Findex#3).

The [maps elements documentation](https://elements.polymer-project.org/elements/google-map) is also unclear about using keys and the [samples](https://elements.polymer-project.org/elements/google-map?view=demo:demo/index.html&active=google-map) do not include them

**Comment by ebidel** [comment]
Yea, it looks like google-maps-directions already supports `apiKey`, `language`, and few others but not `version`. Can you please file a bug against that repo?

https://elements.polymer-project.org/elements/google-map?active=google-map-directions

google-map-search uses the Place API. I don't see a way to specify a version for that API. When using it with google-maps, we use `libraries=places` by default so you'll get the places api.

> I think the most transparent solution would be to require a google-maps-api element with all the params..

Unfortunately, this gets pretty complicated. We have no way of knowing the permutation of parameters people will want to use, how the components are used (esp. as dependencies in other components), etc. 
The root cause of the problem is really one with the Maps API. It uses an older method of loading libs and does not support things like lazy loading components, deferred loading, or progressive enhancement.

> The samples code should be fixed to include the key placeholder.

Thanks. I've fixed this in the source doc. It should be updated on the site the next time we do a push.

**Comment by jiboncom** [comment]
Just a simple solution for the problem of displaying multiple routes  in the same map without having Google Maps API errors: Clone a previous google-map-directions!

First, define a <google-map> and a <google-map-directions> with the same key. This should work without API errors.
`          <google-map 
            latitude="-33.4025252" longitude="-70.7140424" 
            zoom="15" language="es" 
            api-key="..." 
            additional-map-options='{"zoomControl": true, "zoomControlOptions": { "position": "3" }}'
            disable-default-ui
            map="{{map}}">
          </google-map> 
          <google-map-directions 
            api-key="..." 
            map="{{map}}"
            start-address="" end-address=""
            language="es">
          </google-map-directions>  `

Then clone the existing <google-map-directions> element and display your routes
`var newRouteViewer = document.querySelector('google-map-directions').cloneNode();
          Polymer.dom(gmap).appendChild(newRouteViewer); 
var stops = [];
          for (var j = 1; j < route.stops.length-1; j++) {
            stops.push({location: new google.maps.LatLng(route.stops[j].lat, route.stops[j].lon), stopover: true});
          }

          newRouteViewer.startAddress = new google.maps.LatLng(
            route.stops[0].lat, 
            route.stops[0].lon
          );
          newRouteViewer.waypoints = stops;
          newRouteViewer.endAddress = new google.maps.LatLng(
            route.stops[route.stops.length-1].lat, 
            route.stops[route.stops.length-1].lon
          ); `

**Comment by LeongTitanFour** [comment]
> Just a simple solution for the problem of displaying multiple routes in the same map without having Google Maps API errors: Clone a previous google-map-directions!
> 
> First, define a "google-map" and a "google-map-directions" with the same key. This should work without API errors.
> `<google-map latitude="-33.4025252" longitude="-70.7140424" zoom="15" language="es" api-key="..." additional-map-options='{"zoomControl": true, "zoomControlOptions": { "position": "3" }}' disable-default-ui map="{{map}}"> </google-map> <google-map-directions api-key="..." map="{{map}}" start-address="" end-address="" language="es"> </google-map-directions>`
> 
> Then clone the existing "google-map-directions" element and display your routes
> `
> 
> ```
>       var newRouteViewer = document.querySelector("google-map-directions").cloneNode();
>       var stops = [];
>       Polymer.dom(gmap).appendChild(newRouteViewer); 
>       for (var j = 1; j < route.stops.length-1; j++) {
>         stops.push({location: new google.maps.LatLng(route.stops[j].lat, route.stops[j].lon), stopover: true});
>       }
> 
>       newRouteViewer.startAddress = new google.maps.LatLng(
>         route.stops[0].lat, 
>         route.stops[0].lon
>       );
>       newRouteViewer.waypoints = stops;
>       newRouteViewer.endAddress = new google.maps.LatLng(
>         route.stops[route.stops.length-1].lat, 
>         route.stops[route.stops.length-1].lon
>       );`
> ```

what is var route?

**Comment by jiboncom** [comment]
Hi, 
Sorry for being unclear.  var route is just an array of stops objects which include, at least, the latitude and longitude properties (in my case I also included a raw unparsed address). For this use case I make an Ajax request and receive a json like this:

```[
	{
		lat: -33.452605,
		lon: -70.6255178,
		other_info: 'something'
	},
	{
		lat: -33.452603,
		lon: -70.6255474,
		other_info: 'something else'
	},
	{
		lat: -33.452335,
		lon: -70.6255638,
		other_info: 'another thing'
	}
]```

**Comment by LeongTitanFour** [comment]
> Hi,
> Sorry for being unclear. var route is just an array of stops objects which include, at least, the latitude and longitude properties (in my case I also included a raw unparsed address). For this use case I make an Ajax request and receive a json like this:
> 
> ```
> [
> 	{
> 		lat: -33.452605,
> 		lon: -70.6255178,
> 		other_info: 'something'
> 	},
> 	{
> 		lat: -33.452603,
> 		lon: -70.6255474,
> 		other_info: 'something else'
> 	},
> 	{
> 		lat: -33.452335,
> 		lon: -70.6255638,
> 		other_info: 'another thing'
> 	}
> ]
> ```

Thanks :)

**Comment by jiboncom** [comment]
> > Hi,
> > Sorry for being unclear. var route is just an array of stops objects which include, at least, the latitude and longitude properties (in my case I also included a raw unparsed address). For this use case I make an Ajax request and receive a json like this:
> > ```
> > [
> > 	{
> > 		lat: -33.452605,
> > 		lon: -70.6255178,
> > 		other_info: 'something'
> > 	},
> > 	{
> > 		lat: -33.452603,
> > 		lon: -70.6255474,
> > 		other_info: 'something else'
> > 	},
> > 	{
> > 		lat: -33.452335,
> > 		lon: -70.6255638,
> > 		other_info: 'another thing'
> > 	}
> > ]
> > ```
> 
> Thanks :)

Sorry, I had an error. I updated my reply and added the correct code.
