### ISSUE TITLE
Unclosed paper inputs

### ISSUE THREAD

**Issue by Furubu** [googlecodelabs/polymer-maps#12]
https://codelabs.developers.google.com/codelabs/polymer-maps/index.html?index=..%2F..%2Fpolytechnic&viewga=UA-39334307-13#5

In "Build Google Maps Using Web Components & No Code" codelabs I've noticed that the paper inputs tags are unclosed in several examples through steps 5 and 6.

**Comment by abdonrd** [comment]
You are right!

**Comment by ebidel** [comment]
Thanks for reporting. I've updated the underlying doc and this will be fixed on the next codelabs push.
