### ISSUE TITLE
Adding <google-map-directions> causes "You have included the Google Maps API multiple times on this page" error

### ISSUE THREAD

**Issue by tilden** [googlecodelabs/polymer-maps#13]
As far as I can tell, the tutorial does not work past step 4, when the `<google-maps-directions>` element is added. I examined issue #10, which suggested adding the api key to both elements, or removing it from both. Neither caused any effect.

Steps to reproduce:
1. Follow tutorial until step 4

What occurs:
The map may or may not appear (the directions never do), and the console has the following errors:

```
No Google Maps API Key or Client ID specified. See https://developers.google.com/maps/documentation/javascript/get-api-key for instructions to get started with a key or client id.
js?callback=https___maps_googleapis_com_maps_api_js_callback___callback___v_3_exp_libraries_drawing…:102 You have included the Google Maps API multiple times on this page. This may cause unexpected errors.ah @ js?callback=https___maps_googleapis_com_maps_api_js_callback___callback___v_3_exp_libraries_drawing…:102
util.js:221 Google Maps API warning: NoApiKeys https://developers.google.com/maps/documentation/javascript/error-messages#no-api-keys
```

```html
<!doctype html>

<html>
<head>
  <title>PolymerMapsCodelab</title>

  <meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0">
  <meta name="mobile-web-app-capable" content="yes">
  <meta name="apple-mobile-web-app-capable" content="yes">

  <script src="bower_components/webcomponentsjs/webcomponents-lite.min.js"></script>
  <link rel="import" href="bower_components/google-map/google-map.html">
  <link rel="import" href="bower_components/google-map/google-map-directions.html">

  <link rel="stylesheet" href="styles.css">
</head>

<body unresolved>
  <google-map latitude="37.779" longitude="-122.3892"
      api-key="[redacted]" zoom="13" disable-default-ui>
  </google-map>
  <google-map-directions
      start-address="San Francisco"
      end-address="Mountain View"></google-map-directions>
</body>
<script>
  var gmap = document.querySelector('google-map');
  gmap.addEventListener('api-load', function(e) {
    document.querySelector('google-map-directions').map = this.map;
  });
</script>
</body>
</html>
```

**Comment by ebidel** [comment]
The same `api-key="[redacted]"` needs to be used on all maps elements.

The instructions have been fixed in the source doc but the site hasn't picked up the changes yet. We'll update soon!

**Comment by Nitin-Prabhakar** [comment]
#10 

IDK Why, but this surfaces if you do not have a language attribute while calling the element

So having <google-map language="en">

implies you "Have" to ensure language is set in google-map-directions as well.

else, 

you run into the same old 

"you have included google map API multiple times........"  error

**Comment by emielpeperkamp** [comment]
I have the same problem, but using two different sets of elements from google. (the first for places [https://www.webcomponents.org/element/GoogleWebComponents/google-apis/elements/google-maps-api](maps api), the second for directions [https://www.webcomponents.org/element/GoogleWebComponents/google-map/elements/google-map-directions](directions element) The language value seems to matter, because after i changed it did do the query to the api. But the double lib loading error remains.
