### ISSUE TITLE
travelMode Property for <google-map-directions>

### ISSUE THREAD

**Issue by kaona** [googlecodelabs/polymer-maps#5]
Tutorial goes through showing various travel modes. https://www.code-labs.io/codelabs/polymer-maps/index.html?index=..%2F..%2Fchrome-dev-summit&viewga=UA-41980257-1#6

Only driving shows up.  It might be that the travelMode object on line 90 in source here https://github.com/GoogleWebComponents/google-map/blob/master/google-map-directions.html
only has "driving" option in it.

**Comment by bamnet** [comment]
Line 90-something of google-map-directions.html is setting the default value for the travelMode property to `DRIVING`, the `label` being used in the tutorial should be overriding that string based on what is selected in the UI.

**Comment by ebidel** [comment]
Per the last comment. This is WAI
