### ISSUE TITLE
Map API or Client ID missing

### ISSUE THREAD

**Issue by jongmana** [googlecodelabs/polymer-maps#9]
Due to an update of the google-map component, a API key or Client ID now is required (https://github.com/GoogleWebComponents/google-map/issues/269).
This isn't covered by this tutorial yet.

**Comment by ebidel** [comment]
Updated the source doc. It'll be available on our next push of the codelabs site.

**Comment by crhym3** [comment]
This should now be live at https://codelabs.developers.google.com/codelabs/polymer-maps/
